### ISSUE TITLE
Multiple channels fail

### ISSUE THREAD

**Issue by lukapecnik** [amauryval/publish_conda_package_action#1]
Hi,

I am having problems with deploying to conda using multiple channels in the `main.yml` file. I use the following configuration for channels: `Channels: 'conda-forge some-other-channel'`.

After a little investigation I found out that only the first channel is appended in the for loop:

```sh
for CHANNEL in $CHANNELS
do
    conda config --append channels $CHANNEL
done
```

Can you check this out please?

Best regards,
l.

**Comment by amauryval** [comment]
Thank you for your feedback. 
Indeed, I have left something in the entrypoint.sh file !!

The new release will come in few hours.

Best regards
